### ISSUE TITLE
dependencies issues about openpose

### ISSUE THREAD

**Issue by KaifuZ** [akanazawa/motion_reconstruction#1]
I can not find ''openpose/build/examples/openpose/openpose.bin'' in openpose repo, could you tell me where this file or folder is?

**Comment by sxhzju** [comment]
that is Linux version...if you use windows, the path would be something like _**bin\OpenPoseDemo.exe**_..
by the way, I am also trying to figure out this motion_reconstruction and we can exchange some thoughts and tips if you would like to, here is my Email: 470196540@qq.com

**Comment by sxhzju** [comment]
you are cute bro

**Comment by lisa676** [comment]
@Zju-George was you able to run this code?
