### ISSUE TITLE
Is there code about Imitation Learning of training the policy? 

### ISSUE THREAD

**Issue by sxhzju** [akanazawa/motion_reconstruction#2]
I havn't run these two line code because I havn't configure the environment.

> python -m run_openpose

> python -m refine_video

But I guess the first one is to get the json file storing all the keypoints and the second one is to get the bvh and h5 file storing the animation..

The question is, how to train the policy? Is the code for training not uploaded yet?
I'm a newbee about Deep Learning and I will be very appreciated if you have time to answer me.

**Comment by akanazawa** [comment]
Please take a look at the deep mimic code release for this part: https://github.com/xbpeng/DeepMimic
