### ISSUE TITLE
where is the PRETRAINED_MODEL

### ISSUE THREAD

**Issue by sxhzju** [akanazawa/motion_reconstruction#3]
in refiner.py, you need a pretrained_model which name should be Feb12_2100_save75_model.ckpt-667589,
but in hmr the model isn't this so I wonder how can I get it ?

**Comment by akanazawa** [comment]
Hi,
You can find it here:
https://drive.google.com/file/d/1vnAZgwS6DrEC9RNB-KsZzbPvIwJex5b2/view?usp=sharing

Best,

angjoo

**Comment by sxhzju** [comment]
Thans angjoo!

Btw, this model is to smooth the hmr output, so what is the input of the model(which should be the hmr result)? 
Typically, what is hmr result? Because I remember in hmr, you didn't write the results out..

**Comment by akanazawa** [comment]
Hi,

Ah this is the HMR model (should run using hmr code) and no model is necessary to smooth the output since it's just optimization.

Best,

Angjoo
