### ISSUE TITLE
How to get root position

### ISSUE THREAD

**Issue by sxhzju** [akanazawa/motion_reconstruction#5]
How to get root position?
Not rotation or anything, but root position, I saw in your bvhs, you have root position, but in your code, the model didn't predict that thing, so how did you get it?

**Comment by ZhengyiLuo** [comment]
@Zju-George 
Hi George,

Wondering have you find a way to resolve this issue yet? The only way I can think of is to use the camera estimation to get a rough estimate of the root location. Wondering if you have other insights? 

Thanks!

**Comment by sxhzju** [comment]
> @Zju-George
> Hi George,
> 
> Wondering have you find a way to resolve this issue yet? The only way I can think of is to use the camera estimation to get a rough estimate of the root location. Wondering if you have other insights?
> 
> Thanks!

I tried the solution and it works！
